---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        image: borkarrohit/knative-demo-app:v1
        ports:
        - containerPort: 80        
        env:
        - name: REGION
          value: "us"

